port: 8080
log_level: "INFO"

# Настройки CORS
cors:
  allow_origins:
    - "http://localhost:8080"
# Добавить origin сервера
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Requested-With"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 86400  # 24 часа


# Сервисы
auth_service:
  url: "http://backend-svc:8081"
  timeout: 30

course_service:
  url: "http://backend-svc:8081"
  timeout: 30

# Service discovery
eureka:
  url: "http://discovery-server:8761/eureka"
  app_name: "api-gateway"
  instance_ip: "api-gateway"