name: Android Release CI

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name (e.g., 1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up jdk 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add execution permission to gradlew file
        run: chmod u+x gradlew

      - name: Set up keystore file
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: echo "$ANDROID_KEYSTORE" | base64 --decode > cybersec-release.jks

      - name: Build release apk
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Build App Bundle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            lms_android/app/build/outputs/apk/release/app-release.apk
            lms_android/app/build/outputs/bundle/release/app-release.aab
          name: "CyberSec Android Release ${{ github.event.inputs.versionName }}"
          tag_name: ${{ github.event.inputs.versionName }}
          draft: false
          prerelease: false
