name: Android CI

on:
  push:
    branches: [ main ]
    paths:
      - 'lms_android/**'

  pull_request:
    branches: [ main ]
    paths:
      - 'lms_android/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    outputs:
      android_changed: ${{ steps.filter.outputs.android }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            android:
              - 'lms_android/**'

  static-code-analysis:
    name: Perform static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Pull Request Check (ktlint, lint)
        run: ./gradlew pullRequestCheck

  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [ static-code-analysis ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: lms_android/app/build/test-results

  jacoco-report:
    name: Jacoco Report
    needs: [ run-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Generate Jacoco report
        run: ./gradlew jacocoDebugTestReport

      - name: Upload Jacoco HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: lms_android/app/build/reports/jacoco/debug/html

      - name: Jacoco Coverage Summary
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: lms_android/app/build/reports/jacoco/debug/xml/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}

  build-debug-apk:
    name: Build Debug APK
    needs: [ static-code-analysis, run-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lms_cybersecurity.apk
          path: lms_android/app/build/outputs/apk/debug/app-debug.apk