name: Go Lint

on:
  push:
    branches: [main, develop]
    paths:
      - '**.go'

  pull_request:
    branches: [main, develop]
    paths:
      - '**.go'

jobs:
  lint:
    name: Go Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64.8
          args: --timeout=5m --out-format=colored-line-number
