name: Go Lint

on:
  push:
    branches: [main, develop]
    paths:
      - '**.go'

  pull_request:
    branches: [main, develop]
    paths:
      - '**.go'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

      - name: Lint Go code with golangci-lint
        run: |
          golangci-lint run
